### ISSUE TITLE
name conflict with real phpunit

### ISSUE THREAD

**Issue by Schrank** [evert/phpunit-bin#1]
I have installed phpunit globally, so installing this packes brings the following error:

```
Skipped installation of bin phpunit for package evert/phpunit-bin: name conflicts with an existing file
```

I love the idea of the project, so it would be great if you rename the bin file. I can do it myself and submit a PR - I have only to rename the file and fix composer.json, right?

**Comment by evert** [comment]
@seldaek mentioned it would be good idea to name the binary `phpunit-cli` to match `grunt-cli` so I'm all for that!

**Comment by Seldaek** [comment]
Oh no I only meant the package name should be phpunit-cli, but in an ideal world it would be provided by phpunit itself and come with a phpunit binary and thus there wouldn't be a conflict. IMO if you choose to use this package you have to give up on having a globally installed phpunit, so you avoid the conflict.

**Comment by evert** [comment]
I tend to agree with @Seldaek on this. I wanna keep the existing binary.
